version: '3.7'
services:
  stoysv2_web:
    container_name: stoysv2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/
      - ./conf/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./conf/php.ini:/usr/local/etc/php/php.ini